{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.postgres.service.port }}
        envFrom:
        - secretRef:
            name: postgres-secret
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        {{- if .Values.postgres.init.createVisitorTable }}
        - name: postgres-init-sql
          mountPath: /docker-entrypoint-initdb.d
        {{- end }}
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data
      {{- if .Values.postgres.init.createVisitorTable }}
      - name: postgres-init-sql
        configMap:
          name: postgres-init-sql
      {{- end }}
{{- end }}
