apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: {{ if .Values.environment.SPACE | eq "production" }}{{ .Values.server.images.prod }}{{ else }}{{ .Values.server.images.dev }}{{ end }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8135
        env:
        - name: SMTP_USER
          value: {{ .Values.environment.SMTP_USER }}
        - name: SMTP_PASS
          value: {{ .Values.environment.SMTP_PASS }}
        - name: SEND_TO
          value: {{ .Values.environment.SEND_TO }}
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: server-auth-secret
              key: AUTH_SECRET
        - name: ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: server-auth-secret
              key: ADMIN_USERNAME
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: server-auth-secret
              key: ADMIN_PASSWORD
        {{- if .Values.postgres.enabled }}
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: {{ .Values.postgres.service.port | quote }}
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        {{- end }}
