apiVersion: v1
kind: Secret
metadata:
  name: server-auth-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  AUTH_SECRET: {{ required "server.auth.secret is required" .Values.server.auth.secret | quote }}
  ADMIN_USERNAME: {{ required "server.auth.adminUsername is required" .Values.server.auth.adminUsername | quote }}
  ADMIN_PASSWORD: {{ required "server.auth.adminPassword is required" .Values.server.auth.adminPassword | quote }}
